version: 2.1

workflows:
  start_cron:
    jobs: 
     - cron_me

jobs:
  cron_me:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: call API for Email
          command: |
            curl ${EMAIL_SERVERLESS}
      - run:
          name: call API for Text
          command: |
            curl ${TEXT_SERVERLESS}